services:
  postgres:
    image: 'postgres:latest'
    environment:
     POSTGRES_DB: vocabularyBuilderDB
    env_file:
       - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - project_data_vol:/var/lib/postgresql/data


volumes:
  project_data_vol:
    driver: local

networks:
  app-network:
    driver: bridge