--liquibase formatted sql
--changeset adam.zimny:1 labels:DEV

--------------------------------------------
---------------Tables-----------------------
--------------------------------------------

-- Jeśli używasz PostgreSQL, może być konieczne włączenie rozszerzenia UUID
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- 1. Tabela GŁÓWNA: vocabulary_entries (Słownik) - ZMIENIONA NAZWA
CREATE TABLE vocabulary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Podstawowe dane
    word_phrase_en VARCHAR(255) NOT NULL,
    translation_pl VARCHAR(255) NOT NULL,
    part_of_speech VARCHAR(50) NOT NULL,

    -- Status i postępy
    mastery_status VARCHAR(50) NOT NULL,
    correct_answer_streak INTEGER DEFAULT 0,
    total_correct_answers INTEGER DEFAULT 0, -- Zgodne z polem w encji

    -- Kontekst
    context_source VARCHAR(50) NOT NULL,
    source_title VARCHAR(255),
    episode_number INTEGER,
    time_offset_seconds INTEGER,

    -- Metadane
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    -- Ograniczenie unikalności: słowo + część mowy
    CONSTRAINT uk_word_pos UNIQUE (word_phrase_en, part_of_speech)
);

-- 2. Tabela: flashcard_session (Statystyki Fiszek)
CREATE TABLE flashcard_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    count_viewed INTEGER NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE
);

-- 3. Tabela: vocabulary_quiz (Sesje Quizów)
CREATE TABLE vocabulary_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Używamy UUID do publicznego identyfikowania quizu
    quiz_uuid UUID NOT NULL,

    score_correct INTEGER NOT NULL,
    score_total INTEGER NOT NULL,

    -- Precision 5, Scale 2 = np. 85.71
    accuracy_percent NUMERIC(5, 2) NOT NULL,

    duration_seconds INTEGER,
    date_completed TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT uk_quiz_uuid UNIQUE (quiz_uuid)
);

-- 4. Tabela: vocabulary_quiz_item (Szczegóły Pytania)
CREATE TABLE vocabulary_quiz_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Klucze Obce
    vocabulary_quiz_id BIGINT NOT NULL,
    vocabulary_entry_id BIGINT NOT NULL,

    is_correct BOOLEAN NOT NULL,
    user_answer VARCHAR(255),
    correct_answer VARCHAR(255) NOT NULL,

    -- Relacje (Foreign Keys)
    CONSTRAINT fk_quiz_item_quiz FOREIGN KEY (vocabulary_quiz_id) REFERENCES vocabulary_quiz(id),
    CONSTRAINT fk_quiz_item_entry FOREIGN KEY (vocabulary_entry_id) REFERENCES vocabulary_entries(id)
);

--------------------------------------------
---------------Rollback---------------------
--------------------------------------------

--rollback DROP TABLE vocabulary_quiz_item;
--rollback DROP TABLE vocabulary_quiz;
--rollback DROP TABLE flashcard_session;
--rollback DROP TABLE vocabulary_entries;